# Generated by Django 2.2.6 on 2019-10-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191026_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
