# Generated by Django 2.2.6 on 2019-10-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191026_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arriendo',
            old_name='nombre',
            new_name='nombre_completo',
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
    ]
