# Generated by Django 2.2.6 on 2019-11-01 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automovil',
            options={'verbose_name': 'Automovil', 'verbose_name_plural': 'Automoviles'},
        ),
        migrations.AlterField(
            model_name='automovil',
            name='agno',
            field=models.IntegerField(verbose_name='año'),
        ),
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=10)),
                ('telefono', models.IntegerField()),
                ('correo', models.CharField(max_length=250)),
                ('tarjeta', models.IntegerField()),
                ('duracion', models.IntegerField()),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Automovil')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arriendo',
                'verbose_name_plural': 'Arriendos',
            },
        ),
    ]
