# Generated by Django 2.2.6 on 2019-11-20 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191101_1320'),
        ('core', '0005_auto_20191026_0210'),
    ]

    operations = [
    ]
